# Server configuration
# server:
  # port: 8080
  # context-path: /kawaiizumi-ecommence
  # tomcat:
    # max-threads: 20

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kawaiizumi?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 

application.message: Kawaiizumi Web