# Server configuration
# server:
  # port: 8080
  # context-path: /kawaiizumi-ecommence
  # tomcat:
    # max-threads: 20

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/chickendb?useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver 

application.message: Kawaiizumi Web