# Server configuration
# server:
  # port: 8080
  # context-path: /kawaiizumi-ecommence
  # tomcat:
    # max-threads: 20

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
# Using MySQL Server for deployment
  datasource:
    url: jdbc:mysql://mysql:3306/chickendb?useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
# Using H2 Server for development
#  datasource:
#    url:  jdbc:h2:tcp://localhost/~/kawaiizumi
#    username: sa
#    password: 
#    driverClassName:  org.h2.Driver

#Message Configuration
kawaiizumi:
  session:
    chicken-management:
      title: kawaiizumi.chicken-management-title